#13 IO read/write image and PixelWindow drawImage/getImage
lunduniversity/introprog-scalalib pull request #23
Opened 2021-07-23 12:02 UTC by theolundqvist

@bjornregnell

2021-07-23 12:04 UTC, theolundqvist commented
#13

2021-07-25 19:40 UTC, bjornregnell requested changes
Thanks for PR! See comments below.

2021-07-25 19:40 UTC, bjornregnell commented on src/main/scala/introprog/IO.scala
> +    import java.nio.file.{Files, Paths, StandardCopyOption}
Don't need to import StandardCopyOption as not used. Also "DANGER: silently" should be removed as deleting is the sole obvious purpose of this method (whereas move is different as delete there might be a hidden side effect).

2021-07-25 19:40 UTC, bjornregnell commented on src/main/scala/introprog/IO.scala
> +    * Loads an image from file
Forgotten end period in doc comment.

2021-07-25 19:40 UTC, bjornregnell commented on src/main/scala/introprog/PixelWindow.scala
> +    * SLOW! creates image one pixel at a time
Don't shout in comments :).  I propose to remove the part that it is slow, as we do not offer any alternative anyway.

2021-07-25 19:40 UTC, bjornregnell commented on src/main/scala/introprog/PixelWindow.scala
> +    * Returns a screenshot of the window
Forgotten period by end of sentence.

2021-07-25 19:40 UTC, bjornregnell commented on src/main/scala/introprog/PixelWindow.scala
> +    (0 until width).map(w => (0 until height).map(h =>
should be foreach instead of map. Or even better, use Scala 3-syntax with nested `for ... do`.

2021-07-25 19:40 UTC, bjornregnell commented on src/main/scala/introprog/PixelWindow.scala
> +    canvas.withGraphics { g =>
g is not used more than once, so better use `_.drawImage(...` instead. Also use ( instead of { here.

2021-07-26 18:41 UTC, bjornregnell approved these changes

2021-07-26 18:42 UTC, merged