Add rotation to PixelWindow.drawImage
lunduniversity/introprog-scalalib pull request #34
Opened 2021-10-01 12:49 UTC by theolundqvist

Thanks to @JoPoLu for the code.

2021-10-01 13:36 UTC, bjornregnell requested changes

2021-10-01 13:36 UTC, bjornregnell commented on src/main/scala/introprog/PixelWindow.scala
> +    at.rotate(angle, width/2, height/2)
Could we avoid calling rotate if angle is zero?

2021-10-01 13:37 UTC, bjornregnell commented on src/main/scala/introprog/PixelWindow.scala
> +    at.rotate(angle, width/2, height/2)
Is the angle relative or absolute?

2021-10-01 13:39 UTC, bjornregnell commented
Thanks for this enhancement! 
I'm wondering how to interpret the angle param (perhaps improve doc comment?):
Does 0 mean that nothing changes? 
And if so, we could avoid calling rotate if angle == 0 ?
And if 0 means no change then very good, because then this does not break existing code thanks to the default param.

2021-10-02 06:50 UTC, theolundqvist commented
> Thanks for this enhancement!
> I'm wondering how to interpret the angle param (perhaps improve doc comment?):
> Does 0 mean that nothing changes?
> And if so, we could avoid calling rotate if angle == 0 ?
> And if 0 means no change then very good, because then this does not break existing code thanks to the default param.

If `angle` equals 0 then the image will not be rotated, if `angle` equals pi/2 then the image will be rotated 90 degrees clockwise. Would degrees or radians be better for simplicity and cohesion?

I could check if `angle == 0` and then just do `drawImage(img, x, y, width, height)`, would not need to use AffineTransform at all then.

2021-10-02 13:25 UTC, bjornregnell commented
Yes it would be good if we could avoid allocation of affine transformation if it is not needed. 
But I guess it is needed if the width and height is changed? Could that also be checked?
I think radians is best.

2021-10-04 11:39 UTC, theolundqvist commented
> Yes it would be good if we could avoid allocation of affine transformation if it is not needed.
> But I guess it is needed if the width and height is changed? Could that also be checked?
> I think radians is best.

Done

2021-10-04 22:27 UTC, JoPoLu commented
I don't see why we would need an affinetransform if rotation = 0 other than the code would look cleaner if you do not have an if statement. I'm not able to figure out how changing drawImage to using affinetransform internally would break any old code. Don't think it lowers performance by a lot either considering that the normal drawImage also has to scale the Images. I did some tests and It resultet in this:
(rotation was at 0 during said tests)
It Took: 489 ms to complete; 100000 drawings using old/standard drawImage
It Took: 412 ms to complete; 100000 drawings using AffineTransform drawImage
(Note: the answers are within my margin of error, I was not able to do any more tests as I have not yet figure out how to allocate more Ram to the heap :) )
One might take more ram than the other, not sure
Graphics2D might even be using Affinetransform internally when we call the standard version of drawImage(No affinetransform as an argument).

 (Have not been able to find the source code for g2d.drawImage, guess this is the second best. 
![drawImage](https://user-images.githubusercontent.com/13909661/135932439-9462aded-6fc1-4091-8b04-f2e8b00049ba.png)
Taken from: https://docs.oracle.com/javase/7/docs/api/java/awt/Graphics2D.html#drawImage(java.awt.image.BufferedImage,%20java.awt.image.BufferedImageOp,%20int,%20int)

Regarding radians or degrees I think that we should use Radians since all math.<trigfunc> returns radians / takes in radians :)

2021-10-06 14:56 UTC, merged